### ISSUE TITLE
Attempted import error: 'Bezier' is not exported from 'bezier-js'.

### ISSUE THREAD

**Issue by suannaitang** [vasturiano/force-graph#194] opened 2021-05-15 08:34 UTC
./node_modules/force-graph/dist/force-graph.module.js
Attempted import error: 'Bezier' is not exported from 'bezier-js'.
安装force-graph 在页面引入就出现这个问题，降低版本之后还是无法解决

**Comment by vasturiano** [comment] 2021-05-15 11:31
duplicate of https://github.com/vasturiano/force-graph/issues/182

**Closed by vasturiano** 2021-05-15 11:31 UTC
